CREATE TABLE USER_ACCOUNT (
    UID INT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
	Phone VARCHAR(12) UNIQUE NOT NULL
);

CREATE TABLE TABLES (
    TableID INT PRIMARY KEY,
    TableName VARCHAR(255) NOT NULL,
    OwnerID INT,  
    FOREIGN KEY (OwnerID) REFERENCES USER_ACCOUNT(UID)
);

CREATE TABLE USER_ROLES (
    RoleID INT PRIMARY KEY,
    RoleName VARCHAR(255) NOT NULL,
	Role_desc VARCHAR(255),
	UId INT NOT NULL,
	FOREIGN KEY(UId) REFERENCES USER_ACCOUNT(UID)
    );
 
 CREATE TABLE PRIVILEGE (
    PrivilegeID INT PRIMARY KEY,
    PrivilegeName VARCHAR(255) NOT NULL,
    PrivilegeType ENUM('Account', 'Relation') NOT NULL
);

CREATE TABLE ACCOUNT_PRIVILEGE (
    Account_ID INT PRIMARY KEY AUTO_INCREMENT,
    Privilege_Id INT,
    FOREIGN KEY (Privilege_Id) REFERENCES PRIVILEGE(PrivilegeID)
);


CREATE TABLE UR_AP (
    URAP_ID INT PRIMARY KEY AUTO_INCREMENT,
    RoleId INT,
    AP_ID INT,
    FOREIGN KEY (RoleId) REFERENCES USER_ROLES(RoleId),
    FOREIGN KEY (AP_ID) REFERENCES ACCOUNT_PRIVILEGE(Account_ID)
);


CREATE TABLE RELATION_PRIVILEGE (
	Relation_ID INT PRIMARY KEY AUTO_INCREMENT,
    Privilege_Id INT,
    FOREIGN KEY (Privilege_Id) REFERENCES PRIVILEGE(PrivilegeID)
);

CREATE TABLE USER_RELATION_TABLE (
	URT_ID INT PRIMARY KEY,
    RoleId INT,  
    Relation_Id INT,  
    TableId INT,  
    FOREIGN KEY (RoleId) REFERENCES USER_ROLES(RoleID),
    FOREIGN KEY (Relation_Id) REFERENCES RELATION_PRIVILEGE(Relation_ID),
    FOREIGN KEY (TableId) REFERENCES TABLES(TableID)
);
