DROP TABLE IF EXISTS USER_RELATION_TABLE;
DROP TABLE IF EXISTS RELATION_PRIVILEGE;
DROP TABLE IF EXISTS UR_AP;    
DROP TABLE IF EXISTS ACCOUNT_PRIVILEGE;
DROP TABLE IF EXISTS PRIVILEGE;
DROP TABLE IF EXISTS TABLES;
DROP TABLE IF EXISTS USER_ROLES;
DROP TABLE IF EXISTS USER_ACCOUNT;